import type { Metadata } from "next";
import { App } from "@/components";
import { LayoutProvider } from "@/providers/layout-provider";
import "./globals.css";
import { AuthProvider } from "@/providers/auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <LayoutProvider>
        <App>{children}</App>
      </LayoutProvider>
      </AuthProvider>
      
    </html>
  );
}
